#prod db config
# internal db url
#jdbc:postgresql://dpg-d8379k3rjlhs73e89qn0-a/wechatdb?sslmode=require
# external db url
#jdbc:postgresql://dpg-d8379k3rjlhs73e89qn0-a.singapore-postgres.render.com/wechatdb?sslmode=require

spring.datasource.url=jdbc:postgresql://dpg-d8379k3rjlhs73e89qn0-a/wechatdb?sslmode=require
spring.datasource.username=wechatdb_render
spring.datasource.password=3bFRoeSO32PbYwZiLjig0Ldv2o9hqp7M
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.devtools.livereload.enabled=true

# Prevent connections from being closed too early by the cloud provider
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.connection-timeout=30000