spring.application.name=wechat

#aws db config
#spring.datasource.url=jdbc:mysql://database-1.czk42yog8v5o.ap-south-1.rds.amazonaws.com:3306/students_tracker

#local db config
spring.datasource.url=jdbc:mysql://localhost:3306/chatAppDB
spring.datasource.username=chatAppUser
spring.datasource.password=admin
#spring.datasource.url=jdbc:mysql://localhost:3306/chatappdb
#spring.datasource.username=root
#spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.devtools.livereload.enabled=true

#logging config
spring.main.banner-mode=off
#spring.jpa.hibernate.dll-auto=update
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.springframework.jdbc.core=trace
logging.level.org.springframework.security=DEBUG
logging.level.com.creating.chatApplication=DEBUG

#app actuator info config
info.app.name=ChatApplication
management.info.env.enabled=true
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
server.servlet.session.timeout=30m

# Set maximum file upload size
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

#Oauth2 configs

# Google oauth config
spring.security.oauth2.client.registration.google.client-id=129594092407-95krngqhq8cmdpbakrek0ebbaik4q986.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile, email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

# Github oauth config
spring.security.oauth2.client.registration.github.client-id=Ov23lix92m2PRBPbu6ez
spring.security.oauth2.client.registration.github.client-secret=6da5159ace6ab4f178252dbef2337870f9e5e0ce
spring.security.oauth2.client.registration.github.scope=user:email

## Twitter OAuth2 Configuration
#spring.security.oauth2.client.registration.twitter.client-id=SU5EUm45dzI0M3J2NE1CQUM3NkQ6MTpjaQ
#spring.security.oauth2.client.registration.twitter.client-secret=IY7lnP5crgHyJJS0z6AoDRsRd3VzXXR8GqP8zIQLDqt1LN5mYy
#spring.security.oauth2.client.registration.twitter.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.twitter.scope=users.read
#spring.security.oauth2.client.registration.twitter.redirect-uri=http://localhost:8080/login/oauth2/code/twitter
#spring.security.oauth2.client.registration.twitter.provider=twitter
#
## Twitter Provider Configuration
#spring.security.oauth2.client.provider.twitter.authorization-uri=https://twitter.com/i/oauth2/authorize
#spring.security.oauth2.client.provider.twitter.token-uri=https://api.twitter.com/2/oauth2/token
#spring.security.oauth2.client.provider.twitter.user-info-uri=https://api.twitter.com/2/users/me
#spring.security.oauth2.client.provider.twitter.user-name-attribute=id

#email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=wechatcorporations@gmail.com
spring.mail.password=erjb fwkd hlby uxxt 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#bugs -
#create message read by feature, from it fix you have new messages noty
#record a message, text editor, image attachments
#add message id to the messages, so that reply formward can be done easily, on click on a reply, scrollbar should scroll to that message .
#reply/forward the message with attachments
#change whole site font
#add default white chat back .
#new messages notification only appear when unread messages present
#add image attach functionality to it too.
#after account update from settings, chats email should also get updated, both on local and firebase
#add explicit page for global errors
#invite user accept/reject flow, remove email invite confirm, backend flow will remain same
#message seen by, based on this, new message noty
#docker
#elastic search for search in messages
#login with google first time , save password to clipboard
#chat messages duplication fix
